### ISSUE TITLE
FR2: Need durable write

### ISSUE THREAD

**Issue by incubos** [Noxoomo/DBCSC#5]
Noticed a strange effect during stress testing:

``` shell
$ java -Xmx1g -cp DBCSC/target/scala-2.10/classes -jar node.j test/node1
[WARN] [10/07/2013 16:51:51.537] [Node-akka.actor.default-dispatcher-2] [Remoting] Tried to associate with unreachable remote address [akka.tcp://Client@127.0.0.1:2513]. Address is now quarantined, all messages to this address will be delivered to dead letters.
```

I know the reason, but do you?

**Comment by Noxoomo** [comment]
clients went to offline before get response from nodes. Edit communication — now quit says to client to shutdown (for node shutdown type quit in node console), than client sends messages to all nodes about his wish to quit, after getting confirmation it goes offline. Effect still could appear, if quit messages came faster, than other responses
